Repository LEI-2812/SUMMONER_Repo, pull requests merged in 2024-11, with the labels that each got.

#131 소환수 애니메이션 적용 및 코드 수정
  Workpiece/Summoner/Assets/Animation/SummonAnimator.meta
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Attack.anim
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Attack.anim.meta
  Workpiece/Summoner/Assets/Animation/SummonAnimator/EnemyAttack.anim
  Workpiece/Summoner/Assets/Animation/SummonAnimator/EnemyAttack.anim.meta
  Workpiece/Summoner/Assets/Animation/SummonAnimator/EnemySummon.controller
  Workpiece/Summoner/Assets/Animation/SummonAnimator/EnemySummon.controller.meta
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Idle.anim
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Idle.anim.meta
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Summon.controller
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Summon.controller.meta
  Workpiece/Summoner/Assets/Image/GUI/Plate/PlayerPlate 1.png.meta
  Workpiece/Summoner/Assets/Prefabs/EnemyPlate.prefab
  Workpiece/Summoner/Assets/Prefabs/PlayerPlates.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Cat.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/DarkDragon.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Eagle.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/FireSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Fox.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Grass Spirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/HighDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/KingSlime.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/LowDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/QueenSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Rabbit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Skeleton.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Slime.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Snake.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Water Spirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Wolf.prefab
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/getParentSummonImage.cs
Labels: ⚒️Feature Development, 🎨Graphic Styling

#132 소환수가 소환 안 되는 버그 수정
  Workpiece/Summoner/Assets/Prefabs/PlayerPlates.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/DarkDragon.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/FireSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Grass Spirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/HighDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/KingSlime.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/LowDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/QueenSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Skeleton.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Water Spirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Wolf.prefab
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
Labels: ⚒️Feature Development, 🎨Graphic Styling

#133 상태창 버그 수정
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/StatePanel.cs
Labels: 📂Status : In Process

#134 Update 전투 관련 기획서
  Document/전투 시스템 관련 세부 기획서/공격 알고리즘 기획서.pdf
  Document/전투 시스템 관련 세부 기획서/예측 시스템 알고리즘 기획서.pdf
Labels: 📑Document

#135 적 대응 공격 알고리즘 테스트 끝
  Workpiece/Summoner/Assets/Script/Battle/BattleController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusEffect.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/CatAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/SnakeAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#136 전투 화면 애니메이션 적용
  Workpiece/Summoner/Assets/Animation/SummonAnimator/EnemySummon.controller
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Hitted.anim
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Hitted.anim.meta
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Summon.controller
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleAlert.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 🎨Graphic Styling, 🎧Sound Setting

#137 각종 기능 및 에셋 적용
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Attack2030.anim
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Attack2030.anim.meta
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Attack7090.anim
  Workpiece/Summoner/Assets/Animation/SummonAnimator/Attack7090.anim.meta
  Workpiece/Summoner/Assets/Animation/SummonAnimator/DragonSummon.controller
  Workpiece/Summoner/Assets/Animation/SummonAnimator/DragonSummon.controller.meta
  Workpiece/Summoner/Assets/Animation/SummonAnimator/EnemySummon2030.controller
  Workpiece/Summoner/Assets/Animation/SummonAnimator/EnemySummon2030.controller.meta
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Cat.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/DarkDragon.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Eagle.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/FireSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Fox.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Grass Spirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/HighDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/KingSlime.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/LowDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/QueenSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Rabbit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Skeleton.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Slime.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Snake.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Water Spirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Wolf.prefab
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Screen/Stage Select Screen.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/AttackAllEnemiesStrategy.cs
  Workpiece/Summoner/Assets/Script/Stage/StageSelecter.cs
  Workpiece/Summoner/Assets/Script/Story/PlayerMove.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage1_Controller.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage3_Controller.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Story.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: ⚒️Feature Development, 🎨Graphic Styling, 🎧Sound Setting

#138 스테이지 이동 이슈 해결
  Workpiece/Summoner/Assets/Script/Battle/BattleAlert.cs
Labels: ⚒️Feature Development

#143 보호막 이미지 적용
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Cat.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/DarkDragon.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Eagle.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/FireSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Fox.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Grass Spirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/HighDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/KingSlime.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/LowDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/QueenSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Rabbit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Skeleton.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Slime.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Snake.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Water Spirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Wolf.prefab
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 🎨Graphic Styling

#144 이미지 이동 수정
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Cat.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/DarkDragon.prefab
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Story/PlayerMove.cs
Labels: 🎨Graphic Styling

#146 Target Attack Cancel
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
Labels: ⚒️Feature Development

#147 StatusEffect Visual Indicator
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusEffect.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: ⚒️Feature Development

#148 에필로그 이동 가능
  Workpiece/Summoner/Assets/Screen/Pro_Epi Screen 1.unity
  Workpiece/Summoner/Assets/Screen/Pro_Epi Screen 1.unity.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleAlert.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Stage/StageController.cs
  Workpiece/Summoner/Assets/Script/Stage/StageSelecter.cs
  Workpiece/Summoner/Assets/Script/Story/Dialogue/InteractionController.cs
  Workpiece/Summoner/Assets/Script/Story/StoryStage.cs
  Workpiece/Summoner/ProjectSettings/EditorBuildSettings.asset
Labels: ⚒️Feature Development

#149 프롤로그 / 에필로그 씬 구분
  Workpiece/Summoner/Assets/Screen/Epilogue Screen.unity
  Workpiece/Summoner/Assets/Screen/Epilogue Screen.unity.meta
  Workpiece/Summoner/Assets/Screen/Prologue Screen.unity
  Workpiece/Summoner/Assets/Screen/Prologue Screen.unity.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleAlert.cs
  Workpiece/Summoner/Assets/Script/Stage/StageController.cs
  Workpiece/Summoner/Assets/Script/Stage/StageSelecter.cs
  Workpiece/Summoner/Assets/Script/Start Screen/StartScreenEvent.cs
  Workpiece/Summoner/Assets/Script/Story/Dialogue/InteractionController.cs
  Workpiece/Summoner/ProjectSettings/EditorBuildSettings.asset
Labels: ⚒️Feature Development

#150 페이드 아웃 / 감사 화면 수정
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/Thank Screen.unity
  Workpiece/Summoner/Assets/Script/Story/Dialogue/ClicktoMain.cs
  Workpiece/Summoner/Assets/Script/Story/Dialogue/ClicktoMain.cs.meta
  Workpiece/Summoner/Assets/Script/Story/Dialogue/InteractionController.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage5_Controller.cs
Labels: ⚒️Feature Development

#152 상태이상 색상변경 공격 모션중엔 안되게 수정
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: ⚒️Feature Development

#153 특정 공격에 사운드가 적용되지 않던 이슈 수정
  Workpiece/Summoner/Assets/Script/Battle/BattleController.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: ⚒️Feature Development

#154 프롤로그/에필로그 씬 연결 수정
  Workpiece/Summoner/Assets/Screen/Epilogue Screen.unity
  Workpiece/Summoner/Assets/Screen/Prologue Screen.unity
  Workpiece/Summoner/Assets/Screen/Start Screen.unity
Labels: ⚒️Feature Development

#155 몬스터 수치조정 및 앞당겨지지 않는 버그 픽스
  Workpiece/Summoner/Assets/Screen/Start Screen.unity
  Workpiece/Summoner/Assets/Script/Stage/StageSelecter.cs
  Workpiece/Summoner/Assets/Script/Stage/StageText.cs
  Workpiece/Summoner/Assets/Script/Start Screen/StartScreenEvent.cs
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Eagle.cs
  Workpiece/Summoner/Assets/Script/Summons/Fox.cs
  Workpiece/Summoner/Assets/Script/Summons/Rabbit.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/Script/Summons/Wolf.cs
Labels: ⚒️Feature Development

#156 24.11.23 버그픽스
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/TurnController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Fox.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
Labels: ⚒️Feature Development

#157 고양이 특수 공격 모션 수정
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
Labels: ⚒️Feature Development

#158 고양이 특수공격 수치버그 픽스 및 스테이지 배수설정 안되있던거 추가보수
  Workpiece/Summoner/Assets/Script/Battle/BattleController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/SummonController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Enermy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Stage/StageController.cs
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: ⚒️Feature Development

#159 스테이지 저장 안되던 버그 픽스
  Workpiece/Summoner/Assets/Script/Stage/StageController.cs
  Workpiece/Summoner/Assets/Script/Stage/StageSelecter.cs
  Workpiece/Summoner/Assets/Script/Start Screen/StartScreenEvent.cs
Labels: ⚒️Feature Development
