Repository LEI-2812/SUMMONER_Repo, pull requests merged in 2024-10, with the labels that each got.

#54 스테이지별 스토리 씬 구성
  Workpiece/Summoner/Assets/Image/Character/player character/Stage1_Scenario_ani.anim
  Workpiece/Summoner/Assets/Screen/Story Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/Story Screen_1Stage.unity.meta
  Workpiece/Summoner/Assets/Screen/Story Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/Story Screen_2Stage.unity.meta
  Workpiece/Summoner/Assets/Screen/Story Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/Story Screen_3Stage.unity.meta
  Workpiece/Summoner/Assets/Screen/Story Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/Story Screen_5Stage.unity.meta
  Workpiece/Summoner/Assets/Screen/Story Screen_7Stage.unity
  Workpiece/Summoner/Assets/Screen/Story Screen_7Stage.unity.meta
  Workpiece/Summoner/ProjectSettings/EditorBuildSettings.asset
Labels: 🎨Graphic Styling

#55 애니메이션 설정
  Workpiece/Summoner/Assets/Image/Character/player character/Stage1_Scenario_ani.anim
Labels: 🎨Graphic Styling

#72 아군 소환수의 특수공격 구현
  Workpiece/Summoner/Assets/Screen/Fight Screen.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusEffect.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/TargetedAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/PlateController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/PlateController.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/SummonController.cs
  Workpiece/Summoner/Assets/Script/Summons/Eagle.cs
  Workpiece/Summoner/Assets/Script/Summons/Rabbit.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#75 씬 연결 완료(7스테 제외)
  Workpiece/Summoner/Assets/Screen/Pro_Epi Screen.unity
  Workpiece/Summoner/Assets/Screen/Stage Select Screen.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_3Stage.unity
  Workpiece/Summoner/Assets/Script/Stage/StageController.cs
  Workpiece/Summoner/Assets/Script/Start Screen/StartScreenEvent.cs
  Workpiece/Summoner/Assets/Script/Story/Dialogue/InteractionController.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage3_Controller.cs
  Workpiece/Summoner/ProjectSettings/EditorBuildSettings.asset
Labels: ⚒️Feature Development, 🎨Graphic Styling

#81 보호막과 무적 특수공격 추가
  Workpiece/Summoner/Assets/Screen/Fight Screen.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/AttackAllEnemiesStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/ClosestEnemyAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusAttackStrategy.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusEffect.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/TargetedAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/TurnController.cs
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Eagle.cs
  Workpiece/Summoner/Assets/Script/Summons/KingSlime.cs
  Workpiece/Summoner/Assets/Script/Summons/LowDevil.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/Script/Summons/Wolf.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#85 적 소환수의 자동공격 및 등급별 연속공격 구현
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen 1.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusEffect.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Enermy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/TurnController.cs
  Workpiece/Summoner/Assets/Script/Summons/HighDevil.cs
  Workpiece/Summoner/Assets/Script/Summons/KingSlime.cs
  Workpiece/Summoner/Assets/Script/Summons/LowDevil.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#87 전투 - 플레이어의 턴 보완
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen 1.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/TurnController.cs
  Workpiece/Summoner/Assets/TextMesh Pro/Fonts/Silver SDF.asset
Labels: 📂Status : In Process, ⚒️Feature Development, 🎨Graphic Styling

#90 씬 연결 추가
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_1Stage.unity
  Workpiece/Summoner/Assets/Script/Stage/StageController.cs
  Workpiece/Summoner/Assets/Script/Story/Dialogue/InteractionController.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage1_Controller.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Story.cs
  Workpiece/Summoner/ProjectSettings/EditorBuildSettings.asset
Labels: 📂Status : In Process, ⚒️Feature Development

#91 상태창 공격 아이콘 관련 수정 사항
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/StatePanel.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/UpgradeLog2.htm
Labels: 📂Status : In Process, ⚒️Feature Development

#94 소환수 이미지 1차 수정
  Workpiece/Summoner/Assets/Image/summon asset/Summon Sprite Sheet.png
  Workpiece/Summoner/Assets/Image/summon asset/Summon Sprite Sheet.png.meta
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Cat.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Eagle.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Fox.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Rabbit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Snake.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Wolf.prefab
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
Labels: 🎨Graphic Styling

#95 아군과 적 소환수 상태 가져오기
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusEffect.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/TargetedAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Enermy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/PlateController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/PlayerAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/PlayerAttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Summons/LowDevil.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: ⚒️Feature Development

#96 소환수들의 예측공격 리스트반환
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/SpecialAttackInfo.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/PlateController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/PlayerAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/CatAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/CatAttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/EagleAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/EagleAttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/FoxAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/FoxAttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/RabbitAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/RabbitAttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/SnakeAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/SnakeAttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/WolfAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/WolfAttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Eagle.cs
  Workpiece/Summoner/Assets/Script/Summons/Fox.cs
  Workpiece/Summoner/Assets/Script/Summons/Rabbit.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/Script/Summons/Wolf.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#97 혼합 알고리즘 구현 및 버그 수정중
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/TargetedAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/EnermyAttackController.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/PlateController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/PlateController.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/SummonController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/SummonController.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/TurnController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/TurnController.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Enermy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/AttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/AttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/CatAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/FoxAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/PlayerAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/PlayerAttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/RabbitAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Summons/Slime.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#98 화면 추가 구현
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
Labels: 🎨Graphic Styling, 🎧Sound Setting

#103 적 공격 알고리즘 구현
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/AttackAllEnemiesStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/ClosestEnemyAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/IAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/TargetedAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/PlateController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/TurnController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#104 StatePanel 버그 수정 + 알고리즘 수정
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/AttackAllEnemiesStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusEffect.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/TargetedAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Character.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/TurnController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Enermy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/CatAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/EagleAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/FoxAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/IAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/IAttackPrediction.cs.meta
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/PlayerAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/RabbitAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/SnakeAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/WolfAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/StatePanel.cs
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Eagle.cs
  Workpiece/Summoner/Assets/Script/Summons/Fox.cs
  Workpiece/Summoner/Assets/Script/Summons/Rabbit.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/Script/Summons/Wolf.cs
Labels: ⚠️Bug, 📂Status : In Process

#106 보호막 가시성 구현
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/StatePanel.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 🎨Graphic Styling

#107 소환수 이미지 출력 수정
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
Labels: 🎨Graphic Styling

#108 스크립트 수정
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/AttackAllEnemiesStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/PlateController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Enermy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#109 Upload 몬스터 이미지
  Workpiece/Summoner/Assets/Image/Enemy asset/Fire Spirit.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Fire Spirit.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Grass Spirit.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Grass Spirit.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/High Devil.png
  Workpiece/Summoner/Assets/Image/Enemy asset/High Devil.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/King Slime.png
  Workpiece/Summoner/Assets/Image/Enemy asset/King Slime.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Low Devil.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Low Devil.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Monster V.1.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Monster V.1.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Queen Spirit.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Queen Spirit.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Skeleton.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Skeleton.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Slime_Medium_Blue.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Slime_Medium_Blue.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Slime_Medium_Green.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Slime_Medium_Green.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Slime_Medium_Red.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Slime_Medium_Red.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Slime_Medium_White.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Slime_Medium_White.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/Water Spirit.png
  Workpiece/Summoner/Assets/Image/Enemy asset/Water Spirit.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/chomp_idle.png
  Workpiece/Summoner/Assets/Image/Enemy asset/chomp_idle.png.meta
  Workpiece/Summoner/Assets/Image/Enemy asset/satiro-Sheet v1.1.png
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/DarkDragon.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/FireSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Grass Spirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/HighDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/KingSlime.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/LowDevil.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/QueenSpirit.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Skeleton.prefab
  Workpiece/Summoner/Assets/Prefabs/SummonPrefab/Water Spirit.prefab
Labels: 🎨Graphic Styling

#110 사운드 일부 적용
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Screen/Pro_Epi Screen.unity
  Workpiece/Summoner/Assets/Screen/Stage Select Screen.unity
  Workpiece/Summoner/Assets/Screen/Start Screen.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_7Stage.unity
  Workpiece/Summoner/Assets/Screen/Thank Screen.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Menu/Menu.cs
Labels: 🎧Sound Setting

#111 상태창 재소환시 해당 소환수로 변경
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/AttackAllEnemiesStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/StatusEffect.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/AttackLogic/TargetedAttackStrategy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/SummonController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/TurnController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/CatAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/getParentSummonImage.cs
Labels: ⚠️Bug, 📂Status : In Process

#113 지속데미지에 입었을때 데미지가 2배, 반격을 하지 못하던 버그 수정 및 오브젝트 최신화
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#114 사운드 추가 작업
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Screen/Pro_Epi Screen.unity
  Workpiece/Summoner/Assets/Screen/Stage Select Screen.unity
  Workpiece/Summoner/Assets/Screen/Start Screen.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_7Stage.unity
  Workpiece/Summoner/Assets/Screen/Thank Screen.unity
  Workpiece/Summoner/Assets/Script/Option/GamePlayController.cs
  Workpiece/Summoner/Assets/Script/Option/Setting.cs
  Workpiece/Summoner/Assets/Script/Option/VideoController.cs
  Workpiece/Summoner/Assets/Script/Stage/StageController.cs
Labels: 🎧Sound Setting

#115 스테이지 별 배수설정 + 1스테이지 state판넬 오브젝트 할당
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Menu/Menu.cs
  Workpiece/Summoner/Assets/Script/Stage/StageController.cs
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Eagle.cs
  Workpiece/Summoner/Assets/Script/Summons/Fox.cs
  Workpiece/Summoner/Assets/Script/Summons/KingSlime.cs
  Workpiece/Summoner/Assets/Script/Summons/Rabbit.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/Script/Summons/Wolf.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#116 애니메이션 및 스토리보드 수정
  Document/스토리 & 애니메이션 관련 기획서 및 스토리보드/3스테이지 시나리오 및 연출 수정.pdf
  Document/스토리 & 애니메이션 관련 기획서 및 스토리보드/스테이지별 시나리오 스토리보드.pdf
  Document/스토리 & 애니메이션 관련 기획서 및 스토리보드/스토리 컨셉 기획서.pdf
  Document/스토리 & 애니메이션 관련 기획서 및 스토리보드/애니메이션 상세 설명.pdf
  Document/스토리 & 애니메이션 관련 기획서 및 스토리보드/에필로그 시나리오 스토리보드.pdf
  Document/스토리 & 애니메이션 관련 기획서 및 스토리보드/연출 상세 설명.pdf
  Document/스토리 & 애니메이션 관련 기획서 및 스토리보드/프롤로그 시나리오 스토리보드.pdf
  Workpiece/Summoner/Assets/Animation/Stage3_Fox.anim
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_3Stage.unity
Labels: 📑Document, 🎨Graphic Styling

#117 재소환 버그 수정, 재소환된 소환수의 공격여부 수정
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/SummonController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Enermy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/FoxAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Eagle.cs
  Workpiece/Summoner/Assets/Script/Summons/Fox.cs
  Workpiece/Summoner/Assets/Script/Summons/Rabbit.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/Script/Summons/Wolf.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#118 상태창 갱신
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/StatePanel.cs
Labels: 🎨Graphic Styling

#119 사운드 에셋 적용
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/PlateController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/SummonController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/StatePanel.cs
Labels: 🎧Sound Setting

#120 클리어 턴 추가
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleAlert.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/TurnController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
Labels: ⚒️Feature Development

#121 재소환시 체력바 버그 수정
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#126 적 지속데미지로 인한 죽음처리 수정 + 소환수 스킬데미지 배수설정 수정 + 상태창 체력바 버그 수정
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Controller/EnermyAttackController.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Enermy.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Plate.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/StatePanel.cs
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/DarkDragon.cs
  Workpiece/Summoner/Assets/Script/Summons/Eagle.cs
  Workpiece/Summoner/Assets/Script/Summons/Fox.cs
  Workpiece/Summoner/Assets/Script/Summons/GrassSpirit.cs
  Workpiece/Summoner/Assets/Script/Summons/HighDevil.cs
  Workpiece/Summoner/Assets/Script/Summons/LowDevil.cs
  Workpiece/Summoner/Assets/Script/Summons/Rabbit.cs
  Workpiece/Summoner/Assets/Script/Summons/Skeleton.cs
  Workpiece/Summoner/Assets/Script/Summons/Slime.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/Script/Summons/Wolf.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#128 스테이지 선택스크립트 기능 및 역할 분별
  Workpiece/Summoner/Assets/Screen/Pro_Epi Screen.unity
  Workpiece/Summoner/Assets/Screen/Stage Select Screen.unity
  Workpiece/Summoner/Assets/Screen/Start Screen.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/StoryScene/Story Screen_7Stage.unity
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Player.cs
  Workpiece/Summoner/Assets/Script/Stage/StageController.cs
  Workpiece/Summoner/Assets/Script/Stage/StageSelecter.cs
  Workpiece/Summoner/Assets/Script/Stage/StageSelecter.cs.meta
  Workpiece/Summoner/Assets/Script/Start Screen/StartScreenEvent.cs
  Workpiece/Summoner/Assets/Script/Story/Dialogue/InteractionController.cs
  Workpiece/Summoner/Assets/Script/Story/Dialogue/InteractionEvent.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage1_Controller.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage2_Controller.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage3_Controller.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage5_Controller.cs
  Workpiece/Summoner/Assets/Script/Story/StageScenarioController/Stage7_Controller.cs
  Workpiece/Summoner/Assets/Script/Story/StoryChangeImage.cs
  Workpiece/Summoner/Assets/Script/Story/StoryChangeImage.cs.meta
  Workpiece/Summoner/Assets/Script/Story/StoryStage.cs
  Workpiece/Summoner/Assets/Script/Story/StoryStage.cs.meta
  Workpiece/Summoner/Assets/Script/Summons/Cat.cs
  Workpiece/Summoner/Assets/Script/Summons/Eagle.cs
  Workpiece/Summoner/Assets/Script/Summons/Fox.cs
  Workpiece/Summoner/Assets/Script/Summons/Rabbit.cs
  Workpiece/Summoner/Assets/Script/Summons/Snake.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
  Workpiece/Summoner/Assets/Script/Summons/Wolf.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#129 소환수 예측 알고리즘 수정
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/EnermyAlgorithm.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/CatAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/EagleAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/FoxAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/RabbitAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/SnakeAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Battle/BattleLogic/Prediction/WolfAttackPrediction.cs
  Workpiece/Summoner/Assets/Script/Summons/Summon.cs
Labels: 📂Status : In Process, ⚒️Feature Development

#130 이미지 위치 수정 및 턴 출력 UI 디자인
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_1Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_2Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_3Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_4Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_5Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_6Stage.unity
  Workpiece/Summoner/Assets/Screen/FightScene/Fight Screen_7Stage.unity
  Workpiece/Summoner/Assets/TextMesh Pro/Fonts/DNFBitBitv2 SDF.asset
Labels: 🎨Graphic Styling
